name: Build Docker Image CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image      
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
        PORT: 8000
      run: |         
        echo $USER
        echo $PASS
        docker build . --file Dockerfile --tag akashigt/devops-ci/cd-task-2:v1
        docker login -u $USER -p $PASS        
        docker push akashigt/devops-ci/cd-task-2:v1
